export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_FEATURED_PRODUCTS = "LOAD_FEATURED_PRODUCTS";
export const PREV_PRODUCT = "PREV_PRODUCT";
export const NEXT_PRODUCT = "NEXT_PRODUCT";
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const UNLOAD_PRODUCT = "UNLOAD_PRODUCT";
