export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const CREATE_CHECKOUT = "CREATE_CHECKOUT";
export const LOAD_FEATURED_PRODUCTS = "LOAD_FEATURED_PRODUCTS";
export const UPDATE_INDEX = "UPDATE_INDEX";
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const UNLOAD_PRODUCT = "UNLOAD_PRODUCT";
export const LOAD_COLLECTIONS = "LOAD_COLLECTIONS";
